=encoding utf8

# ============== POD 内容介绍===============
# 半途而废的努力是可耻的，生成一个可以生长
# 生态环境，才是目标
# =========================================

# 日期：Tue Aug 30 14:02:39 2011
# 作者: 宋志泉 songzhiquan@hotmail.com

=head1 帮助文件系统 X<帮助文件系统>

将文件组织成可以使用的帮助文档，自己使用。在一个文件夹中。
放置每天的心得和学习笔记，关键字使用 X<keyword> 标志。
使用 POD 格式撰写各种文档，可以方便的拷贝和转移。发布，
查询，全文查询。能让自己学习使用的。

=head2 网站克隆，制作镜像，翻译网站。

网站同步制作中文版本。提供翻译更加准确的中文镜像功能。提供
中文论坛咨询服务，

=head3 脚本调试器

学习编程语言的平台，可以更方便的撰写程序，调试程序。
例如易表，在一个窗口中调试，如果能在VIM中调试，使用Perl的
语言翻译功能，输出调试报告。将Vim进行二次开发，可以在平板电脑等设备上使用。

=head3 圣经阅读器

设计自己的硬件设备，触屏，大屏幕显示，独立硬件设备。

=head2 QQ的启示

WEB
QQ就好像一个在线操作系统，如果网络是免费而且是稳定的话，这种服务就会非常有吸引力。
但是网络费用较高，速度限制。
=cut
# vim:tw=78:ts=8:ft=pod:norl:


