=encoding utf8

=head1 历史记录

认定界符 \s*? 在每次合并正则单元的时候，自动插入中间。
在第一层处理一些问题，比在第二层处理问题要高效的多，越往上。
调用同样的问题越多。
在预处理阶段，将\t替换成空格，比在合并正则表达式后，每次判断的时候，
都考虑中间是 \t 的分隔符要快很多。

分工能提高效率，但接口如果太过复杂，也会降低效率。
层次化能明确分工。
能在较早解决的问题，如果推移到以后解决，将增加解决难度和工作量。
所以在层次处理上，能处理的简单问题，尽量在初期解决。

语法处理前，尽量使用层次明确的预处理，所有在开始显明的问题，都在这个层次
处理。空格替换，分趟处理。

https://github.com/songzan/xml10n 以前的项目
ChinaUnix 论坛的中文文档项目入口
http://bbs.chinaunix.net/viewthread.php?tid=3593804&page=1&extra=#pid21443640

# Vim 制作IDE的文档
http://blog.csdn.net/wooin/article/details/1858917

# Parrot For Perl5 文档
https://github.com/jnthn/blizkost

# Jnthn 的主页
http://www.jnthn.net/perl6/

=head1 帮助文件系统 X<帮助文件系统>

将文件组织成可以使用的帮助文档，自己使用。在一个文件夹中。
放置每天的心得和学习笔记，关键字使用 X<keyword> 标志。
使用 POD 格式撰写各种文档，可以方便的拷贝和转移。发布，
查询，全文查询。能让自己学习使用的。

=head2 网站克隆，制作镜像，翻译网站。

网站同步制作中文版本。提供翻译更加准确的中文镜像功能。提供
中文论坛咨询服务，

=head3 脚本调试器

学习编程语言的平台，可以更方便的撰写程序，调试程序。
例如易表，在一个窗口中调试，如果能在VIM中调试，使用Perl的
语言翻译功能，输出调试报告。将Vim进行二次开发，可以在平板电脑等设备上使用。

=head3 圣经阅读器

设计自己的硬件设备，触屏，大屏幕显示，独立硬件设备。

=head2 QQ的启示

WEB
QQ就好像一个在线操作系统，如果网络是免费而且是稳定的话，这种服务就会非常有吸引力。
但是网络费用较高，速度限制。

=head2 平台文件转换

Unix平台上的文本文件在 Windows上打开，会出现回车符乱码。
只需要将文本在 windows 上重新输入输出一遍即可。

=head2 2011-09-13

设置在线 git 仓库，上传代码到此仓库
https://gitorious.org/~perlvim password:com

=cut

